### ISSUE TITLE
Plex isn't a free font

### ISSUE THREAD

**Issue by OdyX** [blupi-games/planetblupi#109]
Sadly, the "IBM Plex" font isn't considered open-source "enough" by Debian; see https://tracker.debian.org/media/packages/f/fonts-ibm-plex/copyright-6.1.1-1

This sadly needs I can't ship the Plex font files in Debian "as-is", nor depend on the fonts-ibm-plex package (or that would make `planetblupi` a "contrib" package, rather than a "main" package.

**Comment by Skywalker13** [comment]
Arf, that's really a bad news because it's difficult to find a font that works properly with very low resolution in the context of Planet Blupi.

I will try to find something else. Thanks for the report.

**Comment by OdyX** [comment]
FTR, I have patched the 1.15.0 version to use the Noto font variants, and it seemed to work.

**Comment by Skywalker13** [comment]
Arabic and Hebrew are working properly with Noto? I must check that this night. With a lot of fonts, Arabic (especially) looks mostly unreadable in Planet Blupi.

**Comment by Skywalker13** [comment]
Noto Hebrew font is incomplete because latin glyphs are missing.

![image](https://github.com/blupi-games/planetblupi/assets/397862/1b1569ca-bdac-4696-8f3e-2838549a16ae) 
![image](https://github.com/blupi-games/planetblupi/assets/397862/685df674-0189-4a4b-ad98-9a71ad8e336b) 
![image](https://github.com/blupi-games/planetblupi/assets/397862/df6de486-0aa9-47bf-bcb4-2edf9dccd105)


About Noto Arabic, it's better but there are missing glyphs too:

![image](https://github.com/blupi-games/planetblupi/assets/397862/ff3c9f37-f6a7-42fc-a88a-0cee1a0be124)

And there is overflow...

![image](https://github.com/blupi-games/planetblupi/assets/397862/c9cd7aa5-ee6e-42e2-ae0e-cde3db9881db)


I must investigate in other fonts.. It will take time. Now I remember why I use IBM Plex.. the fonts are mostly complete (with latin glyphs) unlike most fonts.

**Comment by Skywalker13** [comment]
For Arabic, here a better font available in Debian Main:

package **fonts-vazirmatn**:  
`/usr/share/fonts/truetype/vazirmatn/Vazirmatn-Regular.ttf`

![image](https://github.com/blupi-games/planetblupi/assets/397862/6277f08c-0bfb-4e5d-9778-7e976be9097e) 
![image](https://github.com/blupi-games/planetblupi/assets/397862/c908ed7d-4bc1-4a52-81b9-95e58c02dabb)

**Comment by Skywalker13** [comment]
And for Hebrew, I tested a lot of font.. but this one looks good:

package **culmus**:  
`/usr/share/fonts/truetype/culmus/NachlieliCLM-Light.otf`

![image](https://github.com/blupi-games/planetblupi/assets/397862/b99181db-dd1b-4fa5-bd72-2e893a7337e2)
![image](https://github.com/blupi-games/planetblupi/assets/397862/12c7827f-bb32-4d94-844a-e987defa9bbc)
![image](https://github.com/blupi-games/planetblupi/assets/397862/69b40c7b-b8ae-4e62-9fc7-856675755cdb)

**Comment by OdyX** [comment]
Great, thanks for the recommendations; I've uploaded 1.15.0-3 with these fonts.
